// Mocks generated by Mockito 5.4.5 from annotations
// in dayliz_app/test/data/repositories/category_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dayliz_app/core/network/network_info.dart' as _i5;
import 'package:dayliz_app/data/datasources/category_remote_data_source.dart'
    as _i3;
import 'package:dayliz_app/data/models/category_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoryModel_0 extends _i1.SmartFake implements _i2.CategoryModel {
  _FakeCategoryModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRemoteDataSource extends _i1.Mock
    implements _i3.CategoryRemoteDataSource {
  MockCategoryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.CategoryModel>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.CategoryModel>>.value(<_i2.CategoryModel>[]),
      ) as _i4.Future<List<_i2.CategoryModel>>);

  @override
  _i4.Future<_i2.CategoryModel> getCategoryById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [id],
        ),
        returnValue: _i4.Future<_i2.CategoryModel>.value(_FakeCategoryModel_0(
          this,
          Invocation.method(
            #getCategoryById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.CategoryModel>);

  @override
  _i4.Future<List<_i2.CategoryModel>> getCategoriesWithSubcategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesWithSubcategories,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.CategoryModel>>.value(<_i2.CategoryModel>[]),
      ) as _i4.Future<List<_i2.CategoryModel>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
