name: 'Setup Node.js Environment'
description: 'Sets up Node.js with caching and validation'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '18'
  working-directory:
    description: 'Working directory for package.json'
    required: true
  cache-dependency-path:
    description: 'Path to package-lock.json or yarn.lock'
    required: false
    default: 'package-lock.json'

outputs:
  node-version:
    description: 'Installed Node.js version'
    value: ${{ steps.node-setup.outputs.node-version }}
  cache-hit:
    description: 'Whether cache was hit'
    value: ${{ steps.node-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: 📦 Setup Node.js
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/${{ inputs.cache-dependency-path }}

    - name: 🔍 Validate Node.js Installation
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "🔍 Validating Node.js installation..."
        node --version
        npm --version
        echo "✅ Node.js validation complete"

    - name: 📊 Node.js Environment Info
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "📊 Node.js Environment Information"
        echo "=================================="
        echo "Node Version: $(node --version)"
        echo "NPM Version: $(npm --version)"
        echo "Working Directory: ${{ inputs.working-directory }}"
        echo "Cache Dependency Path: ${{ inputs.cache-dependency-path }}"
        echo "Package Manager: npm"
